### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by billsacks** [PecanProject/sipnet#10]
Someone inquired about a license for SIPNET. Indeed, I see we don't have a license file. Would it make sense to adopt the standard Pecan Project license if there is one? (I don't have any strong feelings on what the license should be myself.)

**Comment by mdietze** [comment]
Thanks for bringing this up @billsacks.  So PEcAn is in the process of converting from NCSA to BSD-3, so I'd recommend going with the latter for SIPNET.
