### ISSUE TITLE
CI doesn't appear to be executing intended example run

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/sipnet#16]
The file implies that ./sipnet should execute a run, but it isn't clear that this is happening. 

See [.github/workflows/ci.yml](https://github.com/PecanProject/sipnet/blob/master/.github/workflows/ci.yml)

Extra credit: consider updating Ubuntu to latest LTS (currently 24.04)?

**Comment by Alomir** [comment]
So, it _is_ trying to run sipnet - see below - but it is unclear if it is failing, or just not doing anything due to the input settings.

![image](https://github.com/user-attachments/assets/39739a87-8d26-4d2f-a9bd-594f6acf8736)

**Comment by Alomir** [comment]
Running locally, I see the exact same output - and it is generating the expected `niwot.out` file (based on timestamp). So the question is - what do we want to happen here? 

I will try to get an existence check running, though that would be simpler if `niwot.out` were not actually in the repository.

**Comment by dlebauer** [comment]
what do we want to happen here?

First step: a message "niowot.out generated"
Next step: <check diff> "niwot.out generated with expected results"

**Comment by dlebauer** [comment]
closed by #17 and #18
