### ISSUE TITLE
Define format for agronomic events

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/sipnet#20]
For an idea of the information file may need to include see https://github.com/ccmmf/organization/issues/49#issuecomment-2420326774

This file could have a structure similar to climate driver inputs: https://github.com/PecanProject/sipnet/blob/master/docs/sipnet_inputs_outputs.md#3-climate-driver-inputs

Except that each event type will have different parameters. 

Perhaps it could be something like:

```
site year doy event_type event_parameter_1 ... event_parameter_2
0    1998 100 fertilizer urea 200
0    1998 100 tillage    disk 10
0    1998 100 planting   <pft_name>
0    1998 200 harvest    grain
```

**Comment by dlebauer** [comment]
general feedback:

- don't need PFT number
- make event units same as model states
- change 'effect' to 'model representation' and reindent for clarity
- clarify text


updated example above

**Comment by infotroph** [comment]
Tillage: Probably need some additional notion of disturbance intensity (eg chisel plow vs moldboard to same depth)

Planting: 
* I wonder how many parameters actually belong here vs in the PFT file, e.g is the lag from seed planting to germination a property of the PFT or the planting event? 
* For row crops the density info is likely to arrive as either seed(/plant) count per ha or seed weight per ha; conversion from that to C&N will be PFT-specific, yes?

Fertilization: a question that came up in discussion w/Tara and Kelsey was whether C and N interact here; our answer was yes: organic-bound N mineralizes along with the C not independent of it.

Irrigation: 
* Time of day likely to matter!
* need duration of event as well as total amount
* Kelsey: Or alternately depth /fraction of soil profile wetted?

**Comment by dlebauer** [comment]
With respect to the duration for met inputs duration is implied by timestep , for example precipitation is provided in mm / time step. The .clim file has a column for length of timestep, which I believe should be the same as diff(doy+time). 

With events, we don't need to have events followed by non-events that would define the time steps. There are a lot of ways to encode this information, for example:
- add duration to the input file as an event parameter
- add 'rate' to amount eg 2 cm at 1cm/h
- have separate records for irrigation start and stop

We should consider how flexible each is, what aligns best with existing handling of precip, and / or what is easiest to implement

**Comment by mdietze** [comment]
> Tillage: Probably need some additional notion of disturbance intensity (eg chisel plow vs moldboard to same depth)

How specifically would that information be used by SIPNET?

> Planting:
> 
> * I wonder how many parameters actually belong here vs in the PFT file, e.g is the lag from seed planting to germination a property of the PFT or the planting event?
> * For row crops the density info is likely to arrive as either seed(/plant) count per ha or seed weight per ha; conversion from that to C&N will be PFT-specific, yes?

SIPNET has no concept of density or germination. Because of that what we scoped in the CARB conceptual report is to always plant "seedlings", which amounts to initializing a leaf, stem, and root pool of a specific size.

**Comment by infotroph** [comment]
> for met inputs duration is implied by timestep
> we don't need to have events followed by non-events

I think we're agreeing here (correct?) that the met timestep provides an implied duration for each amount of rainfall, but that an irrigation event doesn't have an implied duration so it needs an explicit one. I'm fine specifying that as either a rate or a duration --  "2 cm in 4 hours" and "2 cm at 0.5 cm/hour" are trivial to convert between, so I'd go with whichever will sound more natural to someone reporting their management.

**Comment by dlebauer** [comment]
> we scoped in the CARB conceptual report is to always plant "seedlings", which amounts to initializing a leaf, stem, and root pool of a specific size.

To clarify, the model will always plant seedlings, I envisioned that the mass of seedlings would be equivalent to mass of seeds on the day of planting (i.e. in the abstract, when not considering any control on germination, seeds are just tiny seedlings).

**Comment by mdietze** [comment]
> > we scoped in the CARB conceptual report is to always plant "seedlings", which amounts to initializing a leaf, stem, and root pool of a specific size.
> 
> To clarify, the model will always plant seedlings, I envisioned that the mass of seedlings would be equivalent to mass of seeds on the day of planting (i.e. in the abstract, when not considering any control on germination, seeds are just tiny seedlings).

That's not what I was envisioning. What we wrote in the conceptual report was that we'd go with a very operational definition of "planting", not a physiological one, based on the typical 15% start of spring threshold used in a lot of the phenology literature. That's going to be much further into growth than the conservation of mass from the seeds themselves (especially if you account for germination rate and establishment mortality). We could, in theory, back calculate from the 15% threshold to a germination date, or even to a true planting date, but my pragmatic question would be "why bother?" It's not clear to me that the GPP or rhizosphere-mediated biogeochem during that period is ever going to be large enough to be distinguishable from all the other small errors and biases in the models. If it is, it will show up in the validations against eddy flux and we can use that to decide how far we have to back project.

**Comment by mdietze** [comment]
> @mdietze how do you specify the mass of plants on day of planting?

Well, planting doesn't exist yet in SIPNET, but I envision that we start by backing out what 15% LAI would be, then use SLA to convert that to a leaf pool, and then back out the stem and root pools based on the typical root:shoot, and leaf:root ratios. I'd then test that and recalibrate/tune as needed to match the observed growth trajectories.

**Comment by dlebauer** [comment]
perhaps we can call this 'emergence' instead of planting?

**Comment by infotroph** [comment]
> a very operational definition of "planting", not a physiological one, based on the typical 15% start of spring threshold

I agree this is the right way to get from satellite images to estimated planting dates! But given the event format will also be used for scenarios where management is known from non-RS sources, I think it's worth making a "planting" event line up with common expectations of what "planting" is. 

Maybe another way of putting this is: We need events that are sensible for both seed-planting events and seedling/tree transplanting events. An emergence lag seems to me like an easy way to represent both of those in one event type (lag=0 -> these are seedlings).

**Comment by Alomir** [comment]
From an implementation standpoint, I would expect that the difference between seed-planting and seedling-planting is handled at the pecan level. That is, what we give SIPNET should (?) be the time when we need to make adjustments in the model. Is that 'emergence'?

**Comment by dlebauer** [comment]
This is the updated version as presented in the modeling framework document, still up for iteration 

### Agronomic Events

For managed ecosystems, the following inputs are provided in a file named `events.in` with the following columns:

| col    | parameter   | description                                         | units                                    | notes |
| ------ | ----------- | --------------------------------------------------- | ---------------------------------------- | -------------------------- |
| 1      | loc         | spatial location index                              |                                          | maps to param-spatial file |
| 2      | year        | year of start of this timestep                      |                                          | e.g. 2010  |
| 3      | day         | day of start of this timestep                       | Day of year                              | 1 = Jan 1  |
| 4      | event_type  | type of event                                       |                                          |  one of plant, harv, till, fert, irrig |
| 5...n  | event_param  | parameter associated with event                    |                                          |  see table below |

Event Parameters ("*" indicates required)

- Irrigation
  - event parameters:
    - Amount added* (cm / d) [col 5]
    - type [col 6]
      - 0: canopy
      - 1: soil
      - 2: flood
  - model representation: increases soil moisture
  - notes:
    - irrigation could also directly change the soil moisture content in order. This could be used to represent an irrigation program that sets a moisture range and turns irrigation on at the low end and off at the high end of the range.  
- Fertilization
  - event parameters:
    - Org-N [col 5] (g N / m2)
    - Org-C [col 6] (g C / ha)
    - Min-N [col 7] (g N / m2) (NH4+NO3 in one pool model; NH4 in two pool model)
    - Min-N2 [col 8] (g N / m2) [not used in one pool model, NO3 in two pool model]
  - model representation: increases size of mineral N and litter C and N. Urea-N is assumed to be mineral N or NH4.
  - notes: PEcAn will handle conversion from fertilizer amount and type to mass of N and C allocated to different pools
- Tillage
  - event parameters:
    - SOM decomposition modifier [col 5] (% increase in $K_{dec}$)
    - Litter decomposition modifier [col 6] (% increase in $K_{lit}$)
  - model representation:
    - increase k for one month, amount proportional to depth
    - transfer litter C and N to soil pool
  - notes: could also alter bulk density and other soil properties
- Planting
  - event parameters:
    - emergence lag [col 5] (d) days from planting to prescribed plant size
    - C [col 6] (g C / m2) amount of plant C at emergence
    - N [col 7] (g N / m2) amount of plant N at emergence
  - model representation: C and N pools are allocated to biomass pools using the same allocation parameters as NPP on planting date + emergence lag. Date is provided as 'planting date'; 'emergence lag' indicates the number of days between planting date and the date on which the plant is the specified size. 
  - notes: PFT (crop type) is not an input parameter to SIPNET because SIPNET represents a single PFT as a set of parameters. PEcAn will use PFT as an input and use this information to parameterize SIPNET.
- Harvest
  - event parameters:
    - fraction of aboveground biomass removed* [col 5]
    - fraction of belowground biomass removed [col 6] (default 0)
    - fraction of aboveground biomass transferred to litter pool [col 7] (default = 1-removed)
    - fraction of belowground biomass transferred to litter pool [col 8] (default = 1-removed)
  - model representation:
    - for annuals or plants terminated, 
      - biomass C and N pools are either removed or added to litter (col 5 + col 7 = 1 and col 6 + col 8 = 1).  
    - for perennials: same as above, but some biomass may remain (col 5 + col 7 <= 1 and col 6 + col 8 <= 1; remainder is living).
      - root biomass is only removed for root crops
 
#### Example of events file:

```
1  2022  40  irrig  5   1        # 5cm canopy irrigation on day 40
1  2022  40  fert   100 50 0 0   # fertilized with 10 g / m2 NO3-N and 5 g / m2 NH4-N on day 40
1  2022  35  till   0.2 0.3      # tilled on day 35, soil organic matter pool decomposition rate increases by 20% and soil litter pool decomposition rate increases by 30% 
1  2022  40  plant  10  1        # planting - planting occurs on day 40, after 10 days the plants have emerged with a size of 10 g C/m2 and 1 g N / m2
1  2022  250 harv   0.1          # harvest 10% of aboveground plant biomass on day 250
```
