### ISSUE TITLE
Travis CI for SIPNET

### ISSUE THREAD

**Issue by mdietze** [PecanProject/sipnet#3]
Would be good to set up continuous integration for the SIPNET repo. At a minimum we should confirm that ever PR compiles successfully. Would also be nice to verify that the model can complete a simple, standard run successfully (e.g. Niwot Ridge). Even better would be to verify that the output from that run meets certain sanity checks (e.g. GPP non-negative and not all zeros)

**Comment by robkooper** [comment]
probably should switch to github actions.
